language: node_js
node_js:
  - "stable"
services:
  - postgresql
addons:
    code_climate:
        repo_token: 8b79f2d0c2c56c92d59b9e261428784f515e1e7727b6df20e2d20822c0c80655
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'create database panelfin_test;' -U postgres
  - yarn run db:rollback
after_script:
  - yarn run db:back
script:
  - yarn run coveralls
